### ISSUE TITLE
Bairro (district) Obrigatório no checkout transparente do Pagseguro

### ISSUE THREAD

**Issue by ricardobrg** [claudiosmweb/woocommerce-pagseguro#15]
Não sei se devo adicionar esse issue aqui ou no extra-checkout-fields, mas ao instalar o pagseguro com o extra-checkout-fields, como o bairro não é um campo obrigatório, o checkout transparente dá erro.

Pensei em duas soluções, ou preencher um valor padrão de bairro se o usuário não preencher, já que o pagseguro aceita qualquer valor, ou colocar o bairro como required => true no extra-checkout-fields se o checkout transparente estiver ativado.

**Comment by iCristiano** [comment]
@claudiosanches no formulário de checkout, o campo Bairro aparece como "(opcional)" quando, na verdade, parece ser obrigatório. Você poderia corrigir isso, por favor?
Obrigado!

**Comment by rodrigoocd** [comment]
Ola a todos,

Sr. Claudio Sanches, estou com o mesmo problema agora em setembro 2020. Poderia me ajudar.

PagSeguro: Um erro ocorreu ao processar o seu pagamento, por favor, revise os seus dados e tente novamente. Ou entre em contato conosco para obter assistência. 

codigo de erro:

09-21-2020 @ 11:20:42 - Requesting session ID...
09-21-2020 @ 11:20:42 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => d8296514a6ad4c0e9a7099d7d8384efa
)

09-21-2020 @ 11:22:35 - Requesting direct payment for order 3392 with the following data: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<payment>
  <mode>default</mode>
  <method>creditCard</method>
  <currency>BRL</currency>
  <notificationURL><![CDATA[https://alfapedestais.com.br/wc-api/WC_PagSeguro_Gateway/]]></notificationURL>
  <items>
    <item>
      <id>1</id>
      <description><![CDATA[Produto teste]]></description>
      <amount>5.00</amount>
      <quantity>1</quantity>
    </item>
  </items>
  <reference><![CDATA[WC-3392]]></reference>
  <sender>
    <email><![CDATA[rodrigoocd@hotmail.com]]></email>
    <documents>
      <document>
        <type>CPF</type>
        <value>02656641101</value>
      </document>
    </documents>
    <name><![CDATA[Rodrigo Oliveira]]></name>
    <phone>
      <areaCode>61</areaCode>
      <number>992702281</number>
    </phone>
    <hash>1b7bef513bac1af6cb50a1aa65102e3d1362c2cef7f566989328d6909303cdc7</hash>
  </sender>
  <shipping>
    <type>3</type>
    <address>
      <street><![CDATA[SQN 712/13]]></street>
      <number>6</number>
      <complement><![CDATA[Loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <postalCode>70760640</postalCode>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
    </address>
    <cost>0</cost>
  </shipping>
  <creditCard>
    <token>6a25c46a1097445da2ee231bee3bdd4e</token>
    <installment>
      <quantity>1</quantity>
      <value>5.00</value>
    </installment>
    <holder>
      <name><![CDATA[RODRIGO O C DUTRA]]></name>
      <documents>
        <document>
          <type>CPF</type>
          <value>02656641101</value>
        </document>
      </documents>
      <birthDate>04/11/1988</birthDate>
      <phone>
        <areaCode>61</areaCode>
        <number>992702281</number>
      </phone>
    </holder>
    <billingAddress>
      <street><![CDATA[SQN 712/13]]></street>
      <number>6</number>
      <complement><![CDATA[Loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
      <postalCode>70760640</postalCode>
    </billingAddress>
  </creditCard>
</payment>

09-21-2020 @ 11:22:36 - An error occurred while generating the PagSeguro direct payment: Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [date] => Mon, 21 Sep 2020 14:22:36 GMT
                    [content-type] => application/xml;charset=ISO-8859-1
                    [cache-control] => max-age=180
                    [expires] => Mon, 21 Sep 2020 14:25:36 GMT
                    [vary] => Accept-Encoding,User-Agent
                    [content-encoding] => gzip
                    [strict-transport-security] => max-age=31536000
                    [set-cookie] => TS0136888b=0160ed0a6c678f53565153821e05cd9f34f3c4abee8c1170be0177a0fafeb4f1b8b71a1ec1c2ea236af140e92ca7e7f93fa38182f3; Path=/; Domain=.ws.pagseguro.uol.com.br
                )

        )

    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => TS0136888b
                    [value] => 0160ed0a6c678f53565153821e05cd9f34f3c4abee8c1170be0177a0fafeb4f1b8b71a1ec1c2ea236af140e92ca7e7f93fa38182f3
                    [expires] => 
                    [path] => /
                    [domain] => ws.pagseguro.uol.com.br
                    [host_only] => 
                )

        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [raw] => HTTP/1.1 400 Bad Request
Date: Mon, 21 Sep 2020 14:22:36 GMT
Content-Type: application/xml;charset=ISO-8859-1
Cache-Control: max-age=180
Expires: Mon, 21 Sep 2020 14:25:36 GMT
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000
Connection: close
Set-Cookie: TS0136888b=0160ed0a6c678f53565153821e05cd9f34f3c4abee8c1170be0177a0fafeb4f1b8b71a1ec1c2ea236af140e92ca7e7f93fa38182f3; Path=/; Domain=.ws.pagseguro.uol.com.br
Transfer-Encoding: chunked

<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [date] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:22:36 GMT
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => application/xml;charset=ISO-8859-1
                                        )

                                    [cache-control] => Array
                                        (
                                            [0] => max-age=180
                                        )

                                    [expires] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:25:36 GMT
                                        )

                                    [vary] => Array
                                        (
                                            [0] => Accept-Encoding,User-Agent
                                        )

                                    [content-encoding] => Array
                                        (
                                            [0] => gzip
                                        )

                                    [strict-transport-security] => Array
                                        (
                                            [0] => max-age=31536000
                                        )

                                    [set-cookie] => Array
                                        (
                                            [0] => TS0136888b=0160ed0a6c678f53565153821e05cd9f34f3c4abee8c1170be0177a0fafeb4f1b8b71a1ec1c2ea236af140e92ca7e7f93fa38182f3; Path=/; Domain=.ws.pagseguro.uol.com.br
                                        )

                                )

                        )

                    [status_code] => 400
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    [url] => https://ws.pagseguro.uol.com.br/v2/transactions?email=loja@alfapedestais.com.br&token=82fc8f31-0276-4ea0-8848-5c4defae482b1746485143848a6f0ee48eedfd0076b2a233-c9f5-48b1-9525-18aa57b00429
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                    [TS0136888b] => Requests_Cookie Object
                                        (
                                            [name] => TS0136888b
                                            [value] => 0160ed0a6c678f53565153821e05cd9f34f3c4abee8c1170be0177a0fafeb4f1b8b71a1ec1c2ea236af140e92ca7e7f93fa38182f3
                                            [attributes] => Requests_Utility_CaseInsensitiveDictionary Object
                                                (
                                                    [data:protected] => Array
                                                        (
                                                            [path] => /
                                                            [domain] => ws.pagseguro.uol.com.br
                                                        )

                                                )

                                            [flags] => Array
                                                (
                                                    [creation] => 1600698156
                                                    [last-access] => 1600698156
                                                    [persistent] => 
                                                    [host-only] => 
                                                )

                                            [reference_time] => 1600698156
                                        )

                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)

09-21-2020 @ 11:26:13 - Requesting direct payment for order 3392 with the following data: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<payment>
  <mode>default</mode>
  <method>creditCard</method>
  <currency>BRL</currency>
  <notificationURL><![CDATA[https://alfapedestais.com.br/wc-api/WC_PagSeguro_Gateway/]]></notificationURL>
  <items>
    <item>
      <id>1</id>
      <description><![CDATA[Produto teste]]></description>
      <amount>5.00</amount>
      <quantity>1</quantity>
    </item>
  </items>
  <reference><![CDATA[WC-3392]]></reference>
  <sender>
    <email><![CDATA[rodrigoocd@hotmail.com]]></email>
    <documents>
      <document>
        <type>CPF</type>
        <value>02656641101</value>
      </document>
    </documents>
    <name><![CDATA[Rodrigo Oliveira]]></name>
    <phone>
      <areaCode>61</areaCode>
      <number>992702281</number>
    </phone>
    <hash>1b7bef513bac1af6cb50a1aa65102e3d1362c2cef7f566989328d6909303cdc7</hash>
  </sender>
  <shipping>
    <type>3</type>
    <address>
      <street><![CDATA[SQN 712/13]]></street>
      <number>6</number>
      <complement><![CDATA[Loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <postalCode>70760640</postalCode>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
    </address>
    <cost>0</cost>
  </shipping>
  <creditCard>
    <token>91cb724d4d3d4283b36c251c1e355e48</token>
    <installment>
      <quantity>1</quantity>
      <value>5.00</value>
    </installment>
    <holder>
      <name><![CDATA[RODRIGO O C DUTRA]]></name>
      <documents>
        <document>
          <type>CPF</type>
          <value>02656641101</value>
        </document>
      </documents>
      <birthDate>04/11/1988</birthDate>
      <phone>
        <areaCode>61</areaCode>
        <number>992702281</number>
      </phone>
    </holder>
    <billingAddress>
      <street><![CDATA[SQN 712/13]]></street>
      <number>6</number>
      <complement><![CDATA[Loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
      <postalCode>70760640</postalCode>
    </billingAddress>
  </creditCard>
</payment>

09-21-2020 @ 11:26:14 - An error occurred while generating the PagSeguro direct payment: Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [date] => Mon, 21 Sep 2020 14:26:14 GMT
                    [content-type] => application/xml;charset=ISO-8859-1
                    [cache-control] => max-age=180
                    [expires] => Mon, 21 Sep 2020 14:29:13 GMT
                    [vary] => Accept-Encoding,User-Agent
                    [content-encoding] => gzip
                    [strict-transport-security] => max-age=31536000
                    [set-cookie] => TS018765ea=01ed0a5ec26c7e9c19fdfbd3a26d3ab328383ef8e9bacdf7e620623520f58320c46f7ba0d4b4f4f1af12c6db714e6f2b224f9a7d3b; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
                )

        )

    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => TS018765ea
                    [value] => 01ed0a5ec26c7e9c19fdfbd3a26d3ab328383ef8e9bacdf7e620623520f58320c46f7ba0d4b4f4f1af12c6db714e6f2b224f9a7d3b
                    [expires] => 
                    [path] => /
                    [domain] => ws.pagseguro.uol.com.br
                    [host_only] => 
                )

        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [raw] => HTTP/1.1 400 Bad Request
Date: Mon, 21 Sep 2020 14:26:14 GMT
Content-Type: application/xml;charset=ISO-8859-1
Cache-Control: max-age=180
Expires: Mon, 21 Sep 2020 14:29:13 GMT
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000
Connection: close
Set-Cookie: TS018765ea=01ed0a5ec26c7e9c19fdfbd3a26d3ab328383ef8e9bacdf7e620623520f58320c46f7ba0d4b4f4f1af12c6db714e6f2b224f9a7d3b; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
Transfer-Encoding: chunked

<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [date] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:26:14 GMT
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => application/xml;charset=ISO-8859-1
                                        )

                                    [cache-control] => Array
                                        (
                                            [0] => max-age=180
                                        )

                                    [expires] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:29:13 GMT
                                        )

                                    [vary] => Array
                                        (
                                            [0] => Accept-Encoding,User-Agent
                                        )

                                    [content-encoding] => Array
                                        (
                                            [0] => gzip
                                        )

                                    [strict-transport-security] => Array
                                        (
                                            [0] => max-age=31536000
                                        )

                                    [set-cookie] => Array
                                        (
                                            [0] => TS018765ea=01ed0a5ec26c7e9c19fdfbd3a26d3ab328383ef8e9bacdf7e620623520f58320c46f7ba0d4b4f4f1af12c6db714e6f2b224f9a7d3b; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
                                        )

                                )

                        )

                    [status_code] => 400
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    [url] => https://ws.pagseguro.uol.com.br/v2/transactions?email=loja@alfapedestais.com.br&token=82fc8f31-0276-4ea0-8848-5c4defae482b1746485143848a6f0ee48eedfd0076b2a233-c9f5-48b1-9525-18aa57b00429
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                    [TS018765ea] => Requests_Cookie Object
                                        (
                                            [name] => TS018765ea
                                            [value] => 01ed0a5ec26c7e9c19fdfbd3a26d3ab328383ef8e9bacdf7e620623520f58320c46f7ba0d4b4f4f1af12c6db714e6f2b224f9a7d3b
                                            [attributes] => Requests_Utility_CaseInsensitiveDictionary Object
                                                (
                                                    [data:protected] => Array
                                                        (
                                                            [max-age] => 1600698874
                                                            [path] => /
                                                            [domain] => ws.pagseguro.uol.com.br
                                                        )

                                                )

                                            [flags] => Array
                                                (
                                                    [creation] => 1600698374
                                                    [last-access] => 1600698374
                                                    [persistent] => 
                                                    [host-only] => 
                                                )

                                            [reference_time] => 1600698374
                                        )

                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)

09-21-2020 @ 11:27:59 - Requesting direct payment for order 3392 with the following data: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<payment>
  <mode>default</mode>
  <method>creditCard</method>
  <currency>BRL</currency>
  <notificationURL><![CDATA[https://alfapedestais.com.br/wc-api/WC_PagSeguro_Gateway/]]></notificationURL>
  <items>
    <item>
      <id>1</id>
      <description><![CDATA[Produto teste]]></description>
      <amount>5.00</amount>
      <quantity>1</quantity>
    </item>
  </items>
  <reference><![CDATA[WC-3392]]></reference>
  <sender>
    <email><![CDATA[rodrigoocd@hotmail.com]]></email>
    <documents>
      <document>
        <type>CPF</type>
        <value>02656641101</value>
      </document>
    </documents>
    <name><![CDATA[Rodrigo Oliveira]]></name>
    <phone>
      <areaCode>61</areaCode>
      <number>992702281</number>
    </phone>
    <hash>1b7bef513bac1af6cb50a1aa65102e3d1362c2cef7f566989328d6909303cdc7</hash>
  </sender>
  <shipping>
    <type>3</type>
    <address>
      <street><![CDATA[SQN 712/13]]></street>
      <number>6</number>
      <complement><![CDATA[Loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <postalCode>70760640</postalCode>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
    </address>
    <cost>0</cost>
  </shipping>
  <creditCard>
    <token>37292d4781c54519b444feba19dafac3</token>
    <installment>
      <quantity>1</quantity>
      <value>5.00</value>
    </installment>
    <holder>
      <name><![CDATA[RODRIGO O C DUTRA]]></name>
      <documents>
        <document>
          <type>CPF</type>
          <value>02656641101</value>
        </document>
      </documents>
      <birthDate>04/11/1988</birthDate>
      <phone>
        <areaCode>61</areaCode>
        <number>992702281</number>
      </phone>
    </holder>
    <billingAddress>
      <street><![CDATA[SQN 712/13]]></street>
      <number>6</number>
      <complement><![CDATA[Loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
      <postalCode>70760640</postalCode>
    </billingAddress>
  </creditCard>
</payment>

09-21-2020 @ 11:27:59 - An error occurred while generating the PagSeguro direct payment: Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [date] => Mon, 21 Sep 2020 14:27:59 GMT
                    [content-type] => application/xml;charset=ISO-8859-1
                    [cache-control] => max-age=180
                    [expires] => Mon, 21 Sep 2020 14:30:59 GMT
                    [vary] => Accept-Encoding,User-Agent
                    [content-encoding] => gzip
                    [strict-transport-security] => max-age=31536000
                    [set-cookie] => TS018765ea=01ed0a5ec2c89ce0672d10b08d12d999bbb9dc939a731ea87a66a62a1b17486b2039cda0a23e9077a0dcb34dd28ef9e29e4b0d603a; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
                )

        )

    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => TS018765ea
                    [value] => 01ed0a5ec2c89ce0672d10b08d12d999bbb9dc939a731ea87a66a62a1b17486b2039cda0a23e9077a0dcb34dd28ef9e29e4b0d603a
                    [expires] => 
                    [path] => /
                    [domain] => ws.pagseguro.uol.com.br
                    [host_only] => 
                )

        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [raw] => HTTP/1.1 400 Bad Request
Date: Mon, 21 Sep 2020 14:27:59 GMT
Content-Type: application/xml;charset=ISO-8859-1
Cache-Control: max-age=180
Expires: Mon, 21 Sep 2020 14:30:59 GMT
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000
Connection: close
Set-Cookie: TS018765ea=01ed0a5ec2c89ce0672d10b08d12d999bbb9dc939a731ea87a66a62a1b17486b2039cda0a23e9077a0dcb34dd28ef9e29e4b0d603a; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
Transfer-Encoding: chunked

<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [date] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:27:59 GMT
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => application/xml;charset=ISO-8859-1
                                        )

                                    [cache-control] => Array
                                        (
                                            [0] => max-age=180
                                        )

                                    [expires] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:30:59 GMT
                                        )

                                    [vary] => Array
                                        (
                                            [0] => Accept-Encoding,User-Agent
                                        )

                                    [content-encoding] => Array
                                        (
                                            [0] => gzip
                                        )

                                    [strict-transport-security] => Array
                                        (
                                            [0] => max-age=31536000
                                        )

                                    [set-cookie] => Array
                                        (
                                            [0] => TS018765ea=01ed0a5ec2c89ce0672d10b08d12d999bbb9dc939a731ea87a66a62a1b17486b2039cda0a23e9077a0dcb34dd28ef9e29e4b0d603a; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
                                        )

                                )

                        )

                    [status_code] => 400
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    [url] => https://ws.pagseguro.uol.com.br/v2/transactions?email=loja@alfapedestais.com.br&token=82fc8f31-0276-4ea0-8848-5c4defae482b1746485143848a6f0ee48eedfd0076b2a233-c9f5-48b1-9525-18aa57b00429
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                    [TS018765ea] => Requests_Cookie Object
                                        (
                                            [name] => TS018765ea
                                            [value] => 01ed0a5ec2c89ce0672d10b08d12d999bbb9dc939a731ea87a66a62a1b17486b2039cda0a23e9077a0dcb34dd28ef9e29e4b0d603a
                                            [attributes] => Requests_Utility_CaseInsensitiveDictionary Object
                                                (
                                                    [data:protected] => Array
                                                        (
                                                            [max-age] => 1600698979
                                                            [path] => /
                                                            [domain] => ws.pagseguro.uol.com.br
                                                        )

                                                )

                                            [flags] => Array
                                                (
                                                    [creation] => 1600698479
                                                    [last-access] => 1600698479
                                                    [persistent] => 
                                                    [host-only] => 
                                                )

                                            [reference_time] => 1600698479
                                        )

                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)

09-21-2020 @ 11:42:55 - Checking IPN request...
09-21-2020 @ 11:42:55 - Invalid IPN request: Array
(
)

09-21-2020 @ 11:42:55 - Checking IPN request...
09-21-2020 @ 11:42:55 - Invalid IPN request: Array
(
)

09-21-2020 @ 11:42:55 - Checking IPN request...
09-21-2020 @ 11:42:55 - Invalid IPN request: Array
(
)

09-21-2020 @ 11:43:14 - Checking IPN request...
09-21-2020 @ 11:43:14 - Invalid IPN request: Array
(
)

09-21-2020 @ 11:50:34 - Checking IPN request...
09-21-2020 @ 11:50:34 - Invalid IPN request: Array
(
)

09-21-2020 @ 11:52:36 - Requesting session ID...
09-21-2020 @ 11:52:36 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 142f109045d240978dbfef1477523629
)

09-21-2020 @ 11:55:30 - Requesting direct payment for order 3403 with the following data: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<payment>
  <mode>default</mode>
  <method>creditCard</method>
  <currency>BRL</currency>
  <notificationURL><![CDATA[https://alfapedestais.com.br/wc-api/WC_PagSeguro_Gateway/]]></notificationURL>
  <items>
    <item>
      <id>1</id>
      <description><![CDATA[Produto teste]]></description>
      <amount>5.00</amount>
      <quantity>1</quantity>
    </item>
  </items>
  <reference><![CDATA[WC-3403]]></reference>
  <sender>
    <email><![CDATA[rodrigoocd@hotmail.com]]></email>
    <documents>
      <document>
        <type>CPF</type>
        <value>02656641101</value>
      </document>
    </documents>
    <name><![CDATA[Rodrigo Oliveira]]></name>
    <phone>
      <areaCode>61</areaCode>
      <number>992702281</number>
    </phone>
    <hash>30efdf2deffa2c4f08e984b508b480f3a40b3b261931d12763047629dc5003b4</hash>
  </sender>
  <shipping>
    <type>3</type>
    <address>
      <street><![CDATA[SQN 712/13 bl D lj 6]]></street>
      <number>6</number>
      <complement><![CDATA[loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <postalCode>70760640</postalCode>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
    </address>
    <cost>0</cost>
  </shipping>
  <creditCard>
    <token>cfc5b50c5e88451da0f13fa72f800ea8</token>
    <installment>
      <quantity>1</quantity>
      <value>5.00</value>
    </installment>
    <holder>
      <name><![CDATA[RODRIGO O C DUTRA]]></name>
      <documents>
        <document>
          <type>CPF</type>
          <value>02656641101</value>
        </document>
      </documents>
      <birthDate>04/11/1988</birthDate>
      <phone>
        <areaCode>61</areaCode>
        <number>992702281</number>
      </phone>
    </holder>
    <billingAddress>
      <street><![CDATA[SQN 712/13 bl D lj 6]]></street>
      <number>6</number>
      <complement><![CDATA[loja 6]]></complement>
      <district><![CDATA[Asa Norte]]></district>
      <city><![CDATA[Brasilia]]></city>
      <state>DF</state>
      <country>BRA</country>
      <postalCode>70760640</postalCode>
    </billingAddress>
  </creditCard>
</payment>

09-21-2020 @ 11:55:31 - An error occurred while generating the PagSeguro direct payment: Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [date] => Mon, 21 Sep 2020 14:55:30 GMT
                    [content-type] => application/xml;charset=ISO-8859-1
                    [cache-control] => max-age=180
                    [expires] => Mon, 21 Sep 2020 14:58:31 GMT
                    [vary] => Accept-Encoding,User-Agent
                    [content-encoding] => gzip
                    [strict-transport-security] => max-age=31536000
                    [set-cookie] => TS018765ea=01ed0a5ec217edf5f5cbe5481f614171d84fb31f6af578ad39fa6d996ea80f9d1b35eef2f69561ce66ad102ebae7b948c4903aeab1; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
                )

        )

    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => TS018765ea
                    [value] => 01ed0a5ec217edf5f5cbe5481f614171d84fb31f6af578ad39fa6d996ea80f9d1b35eef2f69561ce66ad102ebae7b948c4903aeab1
                    [expires] => 
                    [path] => /
                    [domain] => ws.pagseguro.uol.com.br
                    [host_only] => 
                )

        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [raw] => HTTP/1.1 400 Bad Request
Date: Mon, 21 Sep 2020 14:55:30 GMT
Content-Type: application/xml;charset=ISO-8859-1
Cache-Control: max-age=180
Expires: Mon, 21 Sep 2020 14:58:31 GMT
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000
Connection: close
Set-Cookie: TS018765ea=01ed0a5ec217edf5f5cbe5481f614171d84fb31f6af578ad39fa6d996ea80f9d1b35eef2f69561ce66ad102ebae7b948c4903aeab1; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
Transfer-Encoding: chunked

<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53085</code><message>payment method unavailable.</message></error></errors>
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [date] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:55:30 GMT
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => application/xml;charset=ISO-8859-1
                                        )

                                    [cache-control] => Array
                                        (
                                            [0] => max-age=180
                                        )

                                    [expires] => Array
                                        (
                                            [0] => Mon, 21 Sep 2020 14:58:31 GMT
                                        )

                                    [vary] => Array
                                        (
                                            [0] => Accept-Encoding,User-Agent
                                        )

                                    [content-encoding] => Array
                                        (
                                            [0] => gzip
                                        )

                                    [strict-transport-security] => Array
                                        (
                                            [0] => max-age=31536000
                                        )

                                    [set-cookie] => Array
                                        (
                                            [0] => TS018765ea=01ed0a5ec217edf5f5cbe5481f614171d84fb31f6af578ad39fa6d996ea80f9d1b35eef2f69561ce66ad102ebae7b948c4903aeab1; Max-Age=500; Path=/; Domain=.ws.pagseguro.uol.com.br
                                        )

                                )

                        )

                    [status_code] => 400
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    [url] => https://ws.pagseguro.uol.com.br/v2/transactions?email=loja@alfapedestais.com.br&token=82fc8f31-0276-4ea0-8848-5c4defae482b1746485143848a6f0ee48eedfd0076b2a233-c9f5-48b1-9525-18aa57b00429
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                    [TS018765ea] => Requests_Cookie Object
                                        (
                                            [name] => TS018765ea
                                            [value] => 01ed0a5ec217edf5f5cbe5481f614171d84fb31f6af578ad39fa6d996ea80f9d1b35eef2f69561ce66ad102ebae7b948c4903aeab1
                                            [attributes] => Requests_Utility_CaseInsensitiveDictionary Object
                                                (
                                                    [data:protected] => Array
                                                        (
                                                            [max-age] => 1600700631
                                                            [path] => /
                                                            [domain] => ws.pagseguro.uol.com.br
                                                        )

                                                )

                                            [flags] => Array
                                                (
                                                    [creation] => 1600700131
                                                    [last-access] => 1600700131
                                                    [persistent] => 
                                                    [host-only] => 
                                                )

                                            [reference_time] => 1600700131
                                        )

                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)
