### ISSUE TITLE
Tradução

### ISSUE THREAD

**Issue by yardz** [claudiosmweb/woocommerce-pagseguro#16]
Blz, eu estava utilizando e achei uma frase bastante exquisita.

#: templates/payment-instructions.php:18
  536  msgid "Please click in the following button to view your Banking Ticket."
  537: msgstr "Por favor, click no botão a seguinte para visualizar o seu boleto bancário."

O ponto é "no botão a seguinte" eu troquei para "no botão a seguir", no caso eu gerei um novo arquivo de tradução, mas estou avisando pois como é uma coisa rápida, acredito que essa mudança possa ser implementada rapidamente.

**Comment by claudiosmweb** [comment]
Corrigido no 2.8.
