### ISSUE TITLE
 Error while parsing the PagSeguro response: String could not be parsed as XML

### ISSUE THREAD

**Issue by rfbastos** [claudiosmweb/woocommerce-pagseguro#17]
Mesmo não utilizando o Pagamento Transparente e sim o LightBox, continuo a receber isto no log

[body] => Forbidden
[response] => Array
(
[code] => 403
[message] => Forbidden
)

A cada 10 vendas 7 são canceladas. 

Saberia me dizer o que mais pode ser feito, já segui 100% o guia de instalação

**Comment by claudiosmweb** [comment]
PagSeguro esta proibindo seu servidor de fazer a requisição.
Pode ser suas vezes erradas ou algo no seu servidor.
