### ISSUE TITLE
Campos nome e sobrenome nao reconhecidos

### ISSUE THREAD

**Issue by josevinagre** [claudiosmweb/woocommerce-pagseguro#18]
Fiz um pedido na loja normalmente, depois instalei o plugin do woocommerce-pagseguro e ao realizar um pedido fica pedindo nome e sobrenome, mesmo com eles preenchidos.

Alguma sugestão?

**Comment by claudiosmweb** [comment]
É impossível acontecer esse problema com este plugin.
Problema deve vir de outro lugar.

**Comment by pashionstudio** [comment]
Também estou com esse problema, @josevinagre você conseguiu resolver? Meu site é o www.dalilaemfuria.com.br
