### ISSUE TITLE
Configurando notificação

### ISSUE THREAD

**Issue by josevinagre** [claudiosmweb/woocommerce-pagseguro#19]
Olá. Como configurar corretamente a comunicação do pagseguro com o plugin? (retorno automatico)

fiz um teste de pagamento usando lightbox, pagamento em debito online. e o pedido continua como aguardando.

**Comment by claudiosmweb** [comment]
Se esta como aguardando é porque funcionou, vai mudar de novo para processando.
Caso o contrário faria como pagamento pendente.

**Comment by ghean** [comment]
Estou com um problema no plugin. Sempre esta ficando como pendente.
Mesmo o pagamento sendo efetuado.
