### ISSUE TITLE
Option to not set order completed after payment is received

### ISSUE THREAD

**Issue by bsalvador** [claudiosmweb/woocommerce-pagseguro#25]
Hello,

I was using your plugin and I had a problem because I sell software licenses, and I had to include the licensing information after the payment is received.
But I want to include this on the order completed email. 
I had to change a little bit the code to avoid to have the order completed after the payment is done.

Maybe should be an interesting idea to have this checkbox "Complete order after payment is approved".

Also, if you can put an option to temporary disable the PAGSEGURO to be shown to people from outside Brazil. I'm located in Brazil but my network is from SWE, so I cannot select pagseguro while developing. I had to change the code for that.

Thanks

**Comment by claudiosmweb** [comment]
No, never... To start this conversation... keep in mind that all payment plugin work that way, changing from pending to processing or to pending to on-hold and then to processing.
"Processing" means that the order is paid and the store is processing to be shipped.

So what are you asking me to do is something goes against all standards!
Your process needs change... Or you will want to change that in all payment gateways will you use?

> Also, if you can put an option to temporary disable the PAGSEGURO to be shown to people from outside Brazil

Just selected use any address from Brazil or change country in the checkout form.
