### ISSUE TITLE
Percentual desconto no boleto

### ISSUE THREAD

**Issue by brunokruger** [claudiosmweb/woocommerce-pagseguro#28]
Olá,

Primeiramente muito obrigado por seu plugin, é genial.
Estou configurando um woocommerce para um cliente onde o mesmo deseja que um produto específico tenha 10% de desconto se for optado a escolha de pagamento por boleto bancário pelo PagSeguro e o outro produto tem 15% de desconto por boleto bancário pelo PagSeguro.

Procurei nas APIs do PagSeguro a programação para descontos para boletos.

<paymentMethodConfigs>
                <paymentMethodConfig>
                    <paymentMethod>
                        <group>boleto</group>
                    </paymentMethod>
                    <configs>
                        <config>
                            <key>DISCOUNT_PERCENT</key>
                            <value>10.00</value>
                        </config>
                    </configs>
                </paymentMethodConfig>
            </paymentMethodConfigs>
...

Mas não encontrei em seu plugin onde eu encaixo esta informação para enviar junto com o XML.

Pergunta 1: Onde eu devo acrescentar esta informação em seu plugin?
Pergunta 2: É possível acrescentar um percentual de desconto para um produto cujo SKU é 001 e outro percentual para outro produto cujo SKU é 002?

Desde já,
Muito obrigado!

Abraços,
Bruno.

**Comment by claudiosmweb** [comment]
Não faz parte do escopo deste plugin.
Se quer dar desconto vá em frete.
