### ISSUE TITLE
Envio de CPF usando WooCommerce API

### ISSUE THREAD

**Issue by luandro** [claudiosmweb/woocommerce-pagseguro#29]
Quando crio uma nova ordem de pagamento usando a API do WooCommerce o campo de CPF fica sempre em branco, fazendo que a ordem seja inválida. Existe uma forma de contornar esse problema?

**Comment by claudiosmweb** [comment]
Não entendi como isso é relacionado com o plugin do PagSeguro...
Parece que esta no lugar errado.

**Comment by luandro** [comment]
O CPF é um campo especial necessário para esse plugin funcionar. Ao criar uma nova ordem na API do WooCommerce esse campo é ignorado. Como se faz a integração dos dois?

**Comment by claudiosmweb** [comment]
CPF não é um campo necessário, pelo menos não para boa parte do plugin, apenas o Checkout Transparente que pede ele, mas este plugin não adiciona qualquer campo de CPF nos pedidos do WooCommerce.

**Comment by luandro** [comment]
Você conhece do mecanismo da API do WooCommerce, não saberia dizer se é possível enviar o valor de CPF por JSON? Sempre que envio os dados por meio da api, o campo não é registrado. Mesmo copiando o json exato de um pedido feito por PHP.

**Comment by claudiosmweb** [comment]
Não é do escopo deste plugin, como eu falei, lugar errado para isso.
