### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by rickhessmann** [claudiosmweb/woocommerce-pagseguro#30]
Tenho um set-up configurado para usar PHP 7 + APCu sobre nGinx.
Roda maravilhosamente bem, mas de uns dias pra cá tenho encontrado problemas com o plugin da PagSeguro retornando erro. Fui aos logs e percebi que, de maneira aleatória, algum produto do carrinho é enviado sem descrição. PagSeguro retorna erro 400, que é Bad Request.

Realmente preciso de ajuda aqui, não faço ideia de onde começar.
Algum problema conhecido?

**Comment by claudiosmweb** [comment]
Só colocar o nome em todos os produtos.

**Comment by rickhessmann** [comment]
O lance é que todos os produtos ja tem nome. E esse problema da descrição ocorre de maneira aleatória.

**Comment by rickhessmann** [comment]
Ok, parece ser um problema com o Zendesk Opcode. Fiz mais de 20 pedidos depois de desativá-lo e não consegui reproduzir o problema.
