### ISSUE TITLE
Notificações

### ISSUE THREAD

**Issue by MarcusMann** [claudiosmweb/woocommerce-pagseguro#37]
Olá tudo bom ? Quando o cliente faz a compra em meu website via Pagseguro (transparente) o pedido ainda fica como sem resposta do pagseguro, ou seja, ele não identifica que o mesmo foi pago. Tem como resolver esse problema? Ou ainda não foi implementado? Obigado.

**Comment by claudiosmweb** [comment]
Veja a FAQ do plugin, lá tem as causas e soluções para isso.
