### ISSUE TITLE
Possível erro na geração do boleto

### ISSUE THREAD

**Issue by crisweiser** [claudiosmweb/woocommerce-pagseguro#8]
07-11-2014 @ 10:26:31 - Requesting session ID...
07-11-2014 @ 10:26:33 - PagSeguro session is valid! The return is: SimpleXMLElement Object
(
    [id] => 4ee9f69e743e4ed1a9083b1518c0dec0
)

07-11-2014 @ 10:26:40 - Error while parsing the PagSeguro response: String could not be parsed as XML
07-11-2014 @ 10:26:40 - An error occurred while generating the PagSeguro direct payment: Array
(
    [headers] => Array
        (
            [date] => Fri, 11 Jul 2014 13:26:38 GMT
            [server] => Apache-Coyote/1.1
            [content-type] => text/plain;charset=ISO-8859-1
            [content-length] => 9
            [vary] => Accept-Encoding,User-Agent
            [connection] => close
        )

```
[body] => Forbidden
[response] => Array
    (
        [code] => 403
        [message] => Forbidden
    )

[cookies] => Array
    (
    )

[filename] => 
```

)

**Comment by raonylopreato** [comment]
Alguém pode me ajudar estou com este problema, 

03-06-2015 @ 07:26:24 - Requesting session ID...
03-06-2015 @ 07:26:25 - Error while parsing the PagSeguro session response: String could not be parsed as XML
03-06-2015 @ 07:26:25 - Session Response: Array
(
    [headers] => Array
        (
            [date] => Fri, 06 Mar 2015 10:26:25 GMT
            [server] => Apache-Coyote/1.1
            [content-type] => text/plain;charset=ISO-8859-1
            [content-length] => 12
            [vary] => User-Agent
            [connection] => close
        )

    [body] => Unauthorized
    [response] => Array
        (
            [code] => 401
            [message] => Unauthorized
        )

    [cookies] => Array
        (
        )

    [filename] => 
)

**Comment by claudiosmweb** [comment]
@raonylopreato só olhar o que você colou aqui:

```
        [code] => 401
        [message] => Unauthorized
```

Você não tem permissão do PagSeguro.
Provavelmente você ignorou o manual do plugin onde tem todas as instruções de instalação e como evitar esse problema.
